version: '3.9'

services:
  rest-service:
    image: if3110-2023-02-36-rest-service:latest
    ports:
      - 5000:5000
    env_file: .env
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/rest'
    depends_on:
      mysql:
        condition: service_healthy
  
  mysql:
    image: mysql:latest
    ports:
      - 5307:3306
    env_file: .env
    volumes:
      - ./mysql:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      - PMA_HOST=mysql
    ports:
      - 5051:80
    depends_on:
      mysql:
        condition: service_healthy